services:
    user-service:
        build: .
        ports:
            - "8080:8080"
        depends_on:
            - postgres
    postgres:
        image: postgres:15-alpine
        container_name: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: user_service
        ports:
            - "5432:5432"
